kind: Service
apiVersion: v1
metadata:
  name: ip
  labels:
    app: ip
spec:
  type: ClusterIP
  selector:
    app: ip
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip
  template:
    metadata:
      labels:
        app: ip
        version: v1
    spec:
      containers:
      - name: ip
        image: ip
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
